version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: iqeas2025
      POSTGRES_PASSWORD: !#%1321^&3451#%^027!R^uigv%^&cyg$%x&Gb$
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    env_file:
      - ./backend/.env   
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/mydb"
    ports:
      - "8080:8080"

volumes:
  pgdata:
